/* Generated By:JavaCC: Do not edit this line. TokenizadorPreprocesadorConstants.java */
package parsermanual.tokenizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TokenizadorPreprocesadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int DIRECTIVA = 10;
  /** RegularExpression Id. */
  int INCLUDE = 11;
  /** RegularExpression Id. */
  int DEFINE = 12;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 13;
  /** RegularExpression Id. */
  int LETRA = 14;
  /** RegularExpression Id. */
  int DIGITO = 15;
  /** RegularExpression Id. */
  int NUMERICO = 16;
  /** RegularExpression Id. */
  int ENTERO = 17;
  /** RegularExpression Id. */
  int DECIMAL = 18;
  /** RegularExpression Id. */
  int COMA = 19;
  /** RegularExpression Id. */
  int PAREN_IZQ = 20;
  /** RegularExpression Id. */
  int PAREN_DER = 21;
  /** RegularExpression Id. */
  int PATH_IZQ = 22;
  /** RegularExpression Id. */
  int PATH_DER = 23;
  /** RegularExpression Id. */
  int COMILLA = 24;
  /** RegularExpression Id. */
  int PATH = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"#\"",
    "\"include\"",
    "\"define\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "<NUMERICO>",
    "<ENTERO>",
    "<DECIMAL>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"\\\"\"",
    "<PATH>",
  };

}
